#!/usr/bin/env bash
# Downloads every image the site needs from the WordPress box into the Zola
# project, so the Zola site has no dependency on the old server.
# Run from /home/jonathan/zola:   bash fetch-assets.sh
set -euo pipefail
cd "$(dirname "$0")"
WP=https://jonathankatzmd.com/wp-content/uploads

# nav icons
D=static/images/nav; mkdir -p "$D"
for f in home doctor video eye human-greeting-proximity; do curl -sSL -o "$D/$f.svg" "$WP/2024/06/$f.svg"; done

# hero cutout, about headshot, favicon
D=static/images/team; mkdir -p "$D"
curl -sSL -o "$D/jonathan-katz-cutout.png" "$WP/2024/06/Jonathan-Katz-full_upscaled-removebg_enlarged-1-3-edited-3.png"
curl -sSL -o "$D/jonathan-katz.jpg" "https://www.katzeneye.com/wp-content/uploads/Jonathan-Katz-full.jpg"
curl -sSL -o static/images/logo.png "$WP/2024/06/cropped-0_cartoon-cat-with-human-eyes-blue-eyes-round-pupi_esrgan-v1-x2plus-270x270.png"

# drug photos
D=static/images/drops; mkdir -p "$D"
curl -sSL -o "$D/apraclonidine.gif" "https://jonathankatzmd.com/wp-content/uploads/2024/07/apraclonidine.gif"
curl -sSL -o "$D/atropine.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/atropine.jpeg"
curl -sSL -o "$D/lumigan.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/lumigan.jpeg"
curl -sSL -o "$D/bimatoprost-03.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/bimatoprost-03.jpg"
curl -sSL -o "$D/alphagan-p-01.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/alphagan-p-01.png"
curl -sSL -o "$D/STL02310.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/STL02310.webp"
curl -sSL -o "$D/alphagan-p-15.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/alphagan-p-15.webp"
curl -sSL -o "$D/Package_31184.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/Package_31184.webp"
curl -sSL -o "$D/COMBIGAN_15mL_Box_Bottle.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/COMBIGAN_15mL_Box_Bottle.png"
curl -sSL -o "$D/novartis-simbrinza.avif" "https://jonathankatzmd.com/wp-content/uploads/2024/07/novartis-simbrinza.avif"
curl -sSL -o "$D/brinzolamide.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/brinzolamide.jpg"
curl -sSL -o "$D/azopt.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/azopt.jpg"
curl -sSL -o "$D/prolensa.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/prolensa.jpg"
curl -sSL -o "$D/bromfenac-0-09.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/bromfenac-0-09.webp"
curl -sSL -o "$D/Carteolol.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/Carteolol.jpg"
curl -sSL -o "$D/cyclopentolate.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/cyclopentolate.jpg"
curl -sSL -o "$D/cyclogyl.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/cyclogyl.webp"
curl -sSL -o "$D/restasis.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/restasis.jpeg"
curl -sSL -o "$D/cequa.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/cequa.jpeg"
curl -sSL -o "$D/difluprednate.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/difluprednate.webp"
curl -sSL -o "$D/durezol.avif" "https://jonathankatzmd.com/wp-content/uploads/2024/07/durezol.avif"
curl -sSL -o "$D/dorz-tim-pf.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/dorz-tim-pf.jpg"
curl -sSL -o "$D/cosopt-pf.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/cosopt-pf.jpeg"
curl -sSL -o "$D/dorz-tim.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/dorz-tim.webp"
curl -sSL -o "$D/dorzolamide.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/dorzolamide.jpg"
curl -sSL -o "$D/erythomycin.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/erythomycin.webp"
curl -sSL -o "$D/fluorometholone.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/fluorometholone.webp"
curl -sSL -o "$D/flurbiprofen-gray-cap.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/10/flurbiprofen-gray-cap.jpg"
curl -sSL -o "$D/flurbiprofen-white-cap.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/10/flurbiprofen-white-cap.webp"
curl -sSL -o "$D/gatifloxacin.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/gatifloxacin.webp"
curl -sSL -o "$D/ketorolac-gray.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/ketorolac-gray.jpg"
curl -sSL -o "$D/ketorolac-white.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/ketorolac-white.jpg"
curl -sSL -o "$D/latanoprost.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/latanoprost.jpg"
curl -sSL -o "$D/vyzulta.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/vyzulta.png"
curl -sSL -o "$D/xiidra.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/xiidra.jpeg"
curl -sSL -o "$D/loteprednol.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/loteprednol.webp"
curl -sSL -o "$D/lotemax.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/lotemax.jpg"
curl -sSL -o "$D/eysuvis.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/eysuvis.png"
curl -sSL -o "$D/xdemvy.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/xdemvy.png"
curl -sSL -o "$D/moxifloxacin.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/moxifloxacin.webp"
curl -sSL -o "$D/vigamox.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/vigamox.jpeg"
curl -sSL -o "$D/neo-poly-dex-gtt.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/neo-poly-dex-gtt.jpg"
curl -sSL -o "$D/neo-poly-dex-ung.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/neo-poly-dex-ung.jpg"
curl -sSL -o "$D/rocklatan.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/rocklatan.webp"
curl -sSL -o "$D/rhopressa.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/rhopressa.webp"
curl -sSL -o "$D/ofloxacin.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/ofloxacin.webp"
curl -sSL -o "$D/ofloxacin-clear-cap.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/ofloxacin-clear-cap.webp"
curl -sSL -o "$D/phenylephrine.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/phenylephrine.png"
curl -sSL -o "$D/pilocarpine.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/pilocarpine.jpg"
curl -sSL -o "$D/polymyxin.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/polymyxin.webp"
curl -sSL -o "$D/pred-pink.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/pred-pink.jpg"
curl -sSL -o "$D/pred-white.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/pred-white.webp"
curl -sSL -o "$D/Pred-Moxi-Brom_8mL.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/Pred-Moxi-Brom_8mL.png"
curl -sSL -o "$D/Pred-Brom.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/Pred-Brom.png"
curl -sSL -o "$D/tafluprost.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/tafluprost.jpg"
curl -sSL -o "$D/zioptan.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/zioptan.jpg"
curl -sSL -o "$D/timolol-clear.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/timolol-clear.webp"
curl -sSL -o "$D/timolol-yellow.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/timolol-yellow.webp"
curl -sSL -o "$D/timoptic.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/timoptic.png"
curl -sSL -o "$D/tobramycin-dex-gtt.webp" "https://jonathankatzmd.com/wp-content/uploads/2024/07/tobramycin-dex-gtt.webp"
curl -sSL -o "$D/tobradex-ung.png" "https://jonathankatzmd.com/wp-content/uploads/2024/07/tobradex-ung.png"
curl -sSL -o "$D/travoprost.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/travoprost.jpg"
curl -sSL -o "$D/travatan-z.jpeg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/travatan-z.jpeg"
curl -sSL -o "$D/tropicamide.jpg" "https://jonathankatzmd.com/wp-content/uploads/2024/07/tropicamide.jpg"

echo "done: $(ls static/images/drops | wc -l) drug photos, nav icons, hero, headshot, favicon"
